package org.example.assistantonsbservlet.api.pubchem.model;

import java.time.LocalDate;

public record FoodAdditiveSubstanceResponseDto(
    int compoundCid,
    String name,
    String synonyms,
    Double molecularWeight,
    String molecularFormula,
    Double polarArea,
    Double complexity,
    Double xlogp,
    Integer heavyAtomCount,
    Integer hBondDonorCount,
    Integer hBondAcceptorCount,
    Integer rotatableBondCount,
    String inchi,
    String smiles,
    String inchiKey,
    String iupacName,
    Double exactMass,
    Double monoisotopicMass,
    Integer charge,
    Integer covalentUnitCount,
    Integer isotopicAtomCount,
    Integer totalAtomStereoCount,
    Integer definedAtomStereoCount,
    Integer undefinedAtomStereoCount,
    Integer totalBondStereoCount,
    Integer definedBondStereoCount,
    Integer undefinedBondStereoCount,
    Integer linkedPubChemLiteratureCount,
    Integer linkedPubChemPatentCount,
    Integer linkedPubChemPatentFamilyCount,
    String meshHeadings,
    String annotationContent,
    Integer annotationTypeCount,
    Integer linkedBioAssays,
    LocalDate createDate,
    String dataSource,
    String dataSourceCategory,
    String taggedByPubChem
) {
}
