CREATE TABLE food_additive_substance (
    compound_cid INT PRIMARY KEY NOT NULL,
    name VARCHAR(1024) NOT NULL,
    synonyms TEXT,
    molecular_weight DOUBLE PRECISION,
    molecular_formula VARCHAR(255),
    polar_area DOUBLE PRECISION,
    complexity DOUBLE PRECISION,
    xlogp DOUBLE PRECISION,
    heavy_atom_count INT,
    h_bond_donor_count INT,
    h_bond_acceptor_count INT,
    rotatable_bond_count INT,
    inchi TEXT,
    smiles TEXT,
    inchi_key TEXT,
    iupac_name TEXT,
    exact_mass DOUBLE PRECISION,
    monoisotopic_mass DOUBLE PRECISION,
    charge INT,
    covalent_unit_count INT,
    isotopic_atom_count INT,
    total_atom_stereo_count INT,
    defined_atom_stereo_count INT,
    undefined_atom_stereo_count INT,
    total_bond_stereo_count INT,
    defined_bond_stereo_count INT,
    undefined_bond_stereo_count INT,
    linked_pubchem_literature_count INT,
    linked_pubchem_patent_count INT,
    linked_pubchem_patent_family_count INT,
    mesh_headings TEXT,
    annotation_content TEXT,
    annotation_type_count INT,
    linked_bioassays INT,
    create_date DATE,
    data_source TEXT,
    data_source_category TEXT,
    tagged_by_pubchem TEXT
);
