name: Build assistant-on-fastapi
on:
  pull_request:
    paths:
      - python/assistant-on-fastapi/**
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
    inputs:
      python-version:
        description: Desired python version
        required: false
        default: "3.12.11"

env:
  PYTHON_VERSION: ${{ inputs.python-version || '3.12.11' }}

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
        
      - name: Install dependencies
        working-directory: python/assistant-on-fastapi
        shell: bash
        run: |
          pip install uv
          make i-dev

      - name: Run checks
        working-directory: python/assistant-on-fastapi
        shell: bash
        run: make lint

      - name: Build
        working-directory: python/assistant-on-fastapi
        shell: bash
        run: uv build
