name: Build assistant-on-fastapi
on:
  pull_request:
    paths:
      - python/assistant-on-fastapi/**
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
    inputs:
      python-version:
        description: Desired python version
        required: false
        default: "3.13.2"

env:
  PYTHON_VERSION: ${{ inputs.python-version || '3.13.2' }}

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
        
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv sync --dev

      - name: Run checks
        shell: bash
        run: pipenv run lint
